apiVersion: v1
kind: Pod
metadata:
  name: compliant-pod
  namespace: test
  labels:
    name: "test_nginx_prod"
spec:
  containers:
    - name: nginx-container
      image: nginx
      resources:
        requests:
          memory: "64Mi"
        limits:
          memory: "128Mi"
          cpu: "500m"
---
apiVersion: v1
kind: Pod
metadata:
  name: non-compliant-pod
  namespace: test
  labels:
    name: "test_wronglabel_test"
spec:
  containers:
    - name: nginx-container
      image: nginx
      resources:
        requests:
          memory: "64Mi"
        limits:
          memory: "128Mi"
          cpu: "500m"
---
apiVersion: v1
kind: Pod
metadata:
  name: missing-label-pod
  namespace: test
spec:
  containers:
    - name: nginx-container
      image: nginx:1.21
      resources:
        requests:
          memory: "64Mi"
        limits:
          memory: "128Mi"
          cpu: "500m"