apiVersion: v1
kind: Pod
metadata:
  name: compliant-pod
  namespace: test
spec:
  containers:
    - name: compliant-container
      image: nginx
      resources:
        limits:
          memory: "128Mi"
        requests:
          memory: "64Mi"
          cpu: "250m"
---
apiVersion: v1
kind: Pod
metadata:
  name: non-compliant-pod
  namespace: test
spec:
  containers:
    - name: non-compliant-container
      image: nginx
