apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-api.aggregator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: aggregator
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: aggregator
    release: {{ .Release.Name }}